### PR TITLE
The class Jeopardy game

### PR DESCRIPTION
**Pull request by yisroelshulman**
This is the work that was done so far by our team.

### CODE REVIEW

**Comment by katychuang** [comment]
Please edit the pull request to merge to a different (new) branch, (perhaps combine your usernames), and then I'll approve it.

**Comment by yisroelshulman** [comment]
> Please edit the pull request to merge to a different (new) branch, (perhaps combine your usernames), and then I'll approve it.

I don't see an option to create a new branch. (I think we don't have the rights to create).

**Comment by katychuang** [comment]
Please  edit the PR and choose branch `team2` as the branch to merge into.

**Comment by yisroelshulman** [comment]
> Please edit the PR and choose branch `team2` as the branch to merge into.

Done.

**Pull request merged**
